### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nikishe** [Wang-Lin-boop/AutoMD#1]
Hello Lin WANG and Hao Yang,
I am struggling making AutoMD to work with our installation of Schrodinger. Are you able to assist me in successfully installing it ? 
kind regards,
Niki

**Comment by Wang-Lin-boop** [comment]
Hi Niki,

Can you describe the problem you are experiencing now? We need to know what happened.

Although we believe you have noticed it, we would like to remind you to refer to the installation tutorial in our [readme](https://github.com/Wang-Lin-boop/AutoMD?tab=readme-ov-file#2-install-the-viparr-and-msys-by-pip).

Lin

**Comment by nikishe** [comment]
Thanks for the response Wang, We installed Schrodinger using [easybuild ](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-3.eb) and using slurm to distribute the jobs over our HPC. And in our use case of just using schrodinger by itself, this works well. 

One of our user has put in a request for AutoMD , and after running the command 

`AutoMD]$ AutoMD -i "*.mae" -S INC -P "chain.name A" -L "res.ptype UNK" -F "OPLS_2005"`

we get the error
**_`CPU Hostfile not found.`_**
 
In our use case slurm takes care of the hosts and we would like to keep it that way (if possible) , so is there a parameter, that can go in the users bashrc to with a list of hosts of their choosing

The reason for this restriction is that all jobs need to run through slurm since we are in a multi tenant set up and running outside slurm would negatively impact other users with errors like out of memory etc

**Comment by Wang-Lin-boop** [comment]
Maybe you can refer to the [following tutorial](https://support.schrodinger.com/s/article/1844) to set up `$SCHRODINGER/schrodinger.hosts` for the slurm.    

> Thanks for the response Wang, We installed Schrodinger using [easybuild ](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-3.eb) and using slurm to distribute the jobs over our HPC. And in our use case of just using schrodinger by itself, this works well.
> 
> One of our user has put in a request for AutoMD , and after running the command
> 
> `AutoMD]$ AutoMD -i "*.mae" -S INC -P "chain.name A" -L "res.ptype UNK" -F "OPLS_2005"`
> 
> we get the error **_`CPU Hostfile not found.`_**
> 
> In our use case slurm takes care of the hosts and we would like to keep it that way (if possible) , so is there a parameter, that can go in the users bashrc to with a list of hosts of their choosing
> 
> The reason for this restriction is that all jobs need to run through slurm since we are in a multi tenant set up and running outside slurm would negatively impact other users with errors like out of memory etc

**Comment by nikishe** [comment]
The link helped the the slurm set up. But Still not getting picked up

```
(schrodinger.ve) [user@node001 [cluster] ~]$ echo $SCHRODINGER
/PATH/Schrodinger/2023-2
(schrodinger.ve) [user@node001 [cluster] ~]$ ls $SCHRODINGER
aacg-v4.4         consensus_homology  fep_absolute_binding  installation_check  ligand_strain     para_testapp       prime_mmgbsa  schrodinger.hosts    tutorials
autots            constant_ph         fep_plus              internal            ligprep           pfam               primex        shape_screen         utilities
bioluminate       covalent_docking    fep_solubility        jaguar              machid            phase_build_qsar   psp-v7.2      shape_screen_gpu     version.txt
bioluminate-v5.1  desmond             gfxinfo               jaguar-v12.0        macromodel        phase_database     qikfit        shape_screen_oned    vsw
blast             desmond-v7.4        glide                 jobcontrol          macromodel-v14.0  phase_find_common  qikprop       sitemap              xtb
bmin              docs                glide-v9.9            jsc                 maestro           phase_fqsar        qikprop-v7.6  ska
canvas-v5.6       easybuild           hppmap                jws                 maestro-v13.6     phase_hypo_refine  qiksim        ssp
combiglide-v6.9   elements            ifd                   knime               materials         phase_qsar         qpld          sta
confgen           epik                ifd-md                knime-v6.2          mmshare-v6.2      phase_screen       qsite         structurebased_adme
confgenx          epik-v6.4           impact                licadmin            mxmd              pipeline           queues        testapp
config            epikx               impact-v9.9           licenses            oned_screen       prime              run           thirdparty
(schrodinger.ve) [user@node001 [cluster] ~]$ AutoMD -i "*.mae" -S INC -P "chain.name A" -L "res.ptype UNK" -F "OPLS_2005"
CPU Hostfile not found.
(schrodinger.ve) [user@node001 [cluster] ~]$ cat  $SCHRODINGER/schrodinger.hosts 
# Schrodinger hosts file
#
# The hosts file consists of a series of entries, each describing a
# 'host' (machine) on which jobs can be run.  See the Installation
# Guide for a description of the settings that can be made here.
#
###############################  NOTE  ################################
# The 'localhost' entry is special:
# * Settings in the 'localhost' entry are implicitly included in
#   every other host entry as well, so settings common to all entries
#   can be placed in the localhost entry.
# * The 'schrodinger:', 'host:' and 'queue:' fields may not be used in
#   the localhost entry.
#######################################################################

#
name:        localhost
tmpdir:      /usr/tmp 


# Slurm 
name: slurm-h100-gpu
host:        localhost
qargs:--partition=gpu-h100 --qos=gpu --gres=gpu:h100:1
tmpdir: /usr/local/tmp 
schrodinger:/PATH/Schrodinger/2023-2/
(schrodinger.ve) [user@node001 [cluster] ~]$ 
```

**Comment by nikishe** [comment]
Even tried to be more verbose

```
AutoMD -i "*.mae" -S INC -P "chain.name A" -L "res.ptype UNK" -F "OPLS_2005" -H ~/.schrodinger/schrodinger.hosts -G ~/.schrodinger/schrodinger.hosts
/users/user/.schrodinger/schrodinger.hosts Hostfile not found
```

**Comment by Wang-Lin-boop** [comment]
> ```
> name: slurm-h100-gpu
> host:        localhost
> qargs:--partition=gpu-h100 --qos=gpu --gres=gpu:h100:1
> tmpdir: /usr/local/tmp 
> schrodinger:/PATH/Schrodinger/2023-2/
> ```

So, your queue name in hosts is `slurm-h100-gpu`.  You need to use `-G slurm-h100-gpu` to specify the GPU queue, and in addition, you need to create a CPU-specific queue and use `-H <cpu queue name>` to specify the CPU queue.

BTW, you need specify the GPU type in hosts. such as:

> ```
> name: slurm-gpu
> host: [headnode.mycluster.com](https://headnode.mycluster.com/) 
> queue: SLURM2.1
> qargs: --partition=all --nodes=1 --ntasks-per-node=%NPROC% --gres=gpu:Tesla:%NPROC%
> tmpdir: /usr/local/tmp 
> schrodinger: /path/to/schrodinger 
> gpgpu: 0, Tesla V100
> gpgpu: 1, Tesla V100
> gpgpu: 2, Tesla V100
> gpgpu: 3, Tesla V100
> ```

Finally, the host file will look something like this:  

Note that the `CPU` and `GPU` in this are just names, you can replace them with whatever you like, e.g. slurm-gpu, V100 and so on.  

```
name: CPU
host: localhost
queue: SLURM2.1
qargs: --partition=all --nodes=1
tmpdir: /usr/local/tmp
schrodinger: /path/to/schrodinger

name: GPU
host: localhost
queue: SLURM2.1
qargs: --partition=all --nodes=1 --ntasks-per-node=%NPROC% --gres=gpu:Tesla:%NPROC%
tmpdir: /usr/local/tmp 
schrodinger: /path/to/schrodinger 
gpgpu: 0, Tesla V100
gpgpu: 1, Tesla V100
gpgpu: 2, Tesla V100
gpgpu: 3, Tesla V100

```

The `CPU` queue is used for submitting CPU tasks, mainly for monitoring task processes and processing data files, and the `GPU` queue is used for performing MD simulation.

**Comment by Wang-Lin-boop** [comment]
With the above approach, you can submit a job at the login node (localhost) and then submit the job to run on the compute node through the job management system.

**Comment by Wang-Lin-boop** [comment]
Make sure the name of your login node is `localhost`, the `host` keyword in the host file refers to the name of your login node.

**Comment by Wang-Lin-boop** [comment]
Please refer to the [official documentation](https://www.schrodinger.com/sites/default/files/s3/release/current/Documentation/html/install_guide/job_setup/job_setup_hosts.htm?tocpath=Getting%20Started%7CRunning%20Schr%C3%B6dinger%20Jobs%7CJob%20Submission%20to%20a%20Cluster%7CJob%20Control%20Guide%20(legacy)%7CAdministrator%20Guide%7CCluster%20Setup%20for%20Schr%C3%B6dinger%20Jobs%7CPreparing%20for%20Remote%20Job%20Submission%7CThe%20Hosts%20File%7C_____0).

**Comment by nikishe** [comment]
Hey Wang, I am calling it a day but just quickly ran automd with your edits and getting better results. I will get back to you tomorrow

```
Your system will only perform 1 simulation.
Note: Parameter OPLS_2005 is vaild.
Note: Parameter cubic is vaild.
Note: Parameter Solute is vaild.
Note: Parameter NPT is vaild.

Jobs will run at slurm-h100-gpu;

Your MD information is as follows:

MIN time: 100 ps
MD time: 100000.0 ps
temperature: 310 K
Repeat: 1
Random numbers list: 3247

Error: mae/cms file not found, please check it. 
```

**Comment by Wang-Lin-boop** [comment]
Maybe you need to check the location of your input file. We need use the `-i` option to specify its path.
